### ISSUE TITLE
Refresh token - NoneType

### ISSUE THREAD

**Issue by Korpip** [yusuf8ahmed/Wsimple#68]
I have some code that takes some time to process on a device that is slow (pi zero w).
I am running into this error.

`Traceback (most recent call last):
  File "pull.py", line 206, in <module>                    ws_jsonpull = ws.find_securities(tsx_db['symbol'][rownum])                                                     File "/usr/local/lib/python3.7/dist-packages/wsimple/api/api.py", line 235, in wrap_manage_tokens                  self.box = self.refresh_token()                     File "/usr/local/lib/python3.7/dist-packages/wsimple/api/api.py", line 192, in refresh_token                      data=tokens[1],                                                                                              TypeError: 'NoneType' object is not subscriptable`

**Comment by yusuf8ahmed** [comment]
Hi Korpip,

Can you send the code (can't do much with just a traceback)

**Comment by yusuf8ahmed** [comment]
Hi Korpip,

Can you reply with the code the is causing this error (can't do much with just a traceback)

**Comment by Korpip** [comment]
I will have to look I to this.  I thought updating my Python library's would correct this and boy did I just break every other python script I am running.

**Comment by Korpip** [comment]
`#test.py
from datetime import datetime
from time import sleep
print("Importing wsimple")
from wsimple.api import Wsimple

def get_otp():
    return input("Enter otpnumber: \n>>>")

email = "email"
password = "password"

ws = Wsimple(email, password, otp_callback=get_otp)
startTime = datetime.now()
lastTime = datetime.now()
print("Start time is " + str(startTime))
while 1 > 0:
    lastTime = datetime.now()
    print("Current time is " + str(lastTime))
    print(ws.find_securities("GOOG")) 
    timeDif = lastTime - startTime
    print("Total run time is " + str(timeDif))
    sleep(60)

`

After about a Total run time of 1:44:45.337612 if got 
`2021-05-08 22:34:35.120 | INFO     | wsimple.api.api:wrap_manage_tokens:236 - Manage Tokens: TokensBox(access_token='token', refresh_token='token thing', access_expires=datetime.datetime(2021, 5, 8, 22, 48, 49)) ('GOOG',) {}
Traceback (most recent call last):
  File "test.py", line 20, in <module>
    print(ws.find_securities("GOOG"))
  File "/home/pi/.local/lib/python3.7/site-packages/wsimple/api/api.py", line 240, in wrap_manage_tokens
    self.box = self.refresh_token(tokens=kwargs["tokens"])
KeyError: 'tokens'`

I got about "Total run time is 1:44:45.337612" from this code.  My goal is to process everything on the TSX against what is available on WealthSimple.

**Comment by yusuf8ahmed** [comment]
Hi Korkip, just fixed it in version 3.0.1 should now be working with no problems.

```bash
pip install -U wsimple
```
